### ISSUE TITLE
Whoops bei Unify code quality

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexfactor#102]
**Whoops bei Unify code quality**

![image](https://github.com/FriendsOfREDAXO/rexfactor/assets/330560/48c13b3d-7dcc-407b-b491-9b56304f866f)

REDAXO: siehe unten System-Report ...
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?** Ja

Habe per dump rausgefunden dass im JSON eine Warning ausgegeben wird.

![image2](https://github.com/FriendsOfREDAXO/rexfactor/assets/330560/841a1938-0927-447e-aba7-d6fd0fe28bb7)

Evtl. kann man ja die Warnings per Option unterdrücken bzw. gibt es auch eine Option für **InlineHTML**

In der theme.php ist HTML sowie auch CSS und JavaScript vorhanden.

**InvalidArgumentException:** Invalid json: Syntax error
**File:** redaxo\src\addons\rexfactor\lib\RectorResult.php
**Line:** 24

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                          | Line     |
| -------------------------------------------- | --------------------------------------------- | -------- |
| rexfactor\RectorResult->__construct          | redaxo\src\addons\rexfactor\lib\RexFactor.php | 150      |
| rexfactor\RexFactor::runRexFactor            | redaxo\src\addons\rexfactor\pages\preview.php | 53       |
| require                                      | redaxo\src\core\lib\packages\package.php      | 233      |
| rex_package->includeFile                     | redaxo\src\core\lib\be\controller.php         | 503      |
| rex_be_controller::{closure}                 | redaxo\src\core\lib\util\timer.php            | 56       |
| rex_timer::measure                           | redaxo\src\core\lib\be\controller.php         | 485      |
| rex_be_controller::includePath               | redaxo\src\core\lib\be\controller.php         | 453      |
| rex_be_controller::includeCurrentPageSubPath | redaxo\src\addons\rexfactor\pages\index.php   | 13       |
| require                                      | redaxo\src\core\lib\packages\package.php      | 233      |
| rex_package->includeFile                     | redaxo\src\core\lib\be\controller.php         | 503      |
| rex_be_controller::{closure}                 | redaxo\src\core\lib\util\timer.php            | 56       |
| rex_timer::measure                           | redaxo\src\core\lib\be\controller.php         | 485      |
| rex_be_controller::includePath               | redaxo\src\core\lib\be\controller.php         | 436      |
| rex_be_controller::includeCurrentPage        | redaxo\src\core\backend.php                   | 241      |
| require                                      | redaxo\src\core\boot.php                      | 155      |
| require                                      | redaxo\index.php                              | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.0, MariaDB 10.4.14)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.0      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.14 |
| Character set | utf8mb4         |

| Server        |               |
| ------------: | :------------ |
|            OS | WINNT         |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.46 |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/114.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | yes              |

| Packages            |            |
| ------------------: | :--------- |
|           aceeditor | 1.2.1      |
|        activity_log | 0.0.2      |
|             adminer | 1.9.3      |
|              backup | 2.9.0      |
|            be_style | 3.2.0      |
| be_style/customizer | 3.2.0      |
|     be_style/redaxo | 3.2.0      |
|          cheatsheet | 0.0.1      |
|     consent_manager | 4.1.4      |
|             cronjob | 2.10.0     |
|          demo_addon | 1.3.0      |
|         insert_text | 2.0.1      |
|             install | 2.11.1     |
|       media_manager | 2.14.0     |
|           mediapool | 2.13.0     |
|            metainfo | 2.10.0     |
|           phpmailer | 2.12.0     |
|          properties | 1.3.3      |
|          rex_gitapi | 0.0.1      |
|           rexfactor | 0.1.11     |
|             rexstan | 1.0.121    |
|               sprog | 1.5.1      |
|           structure | 2.15.0     |
|   structure/content | 2.15.0     |
|           thumbhash | 1.0.0      |
|               users | 2.10.0     |

</details>

**Comment by aeberhard** [comment]
Noch vergessen. In vorherigen rexfactor-Versionen gab es hier keinen Whoops!

**Comment by staabm** [comment]
in https://github.com/FriendsOfREDAXO/rexfactor/pull/104 wurde die rector lib aktualisiert. kannst du bitte nochmal testen ob der fehler noch besteht?

**Comment by staabm** [comment]
Related upstream issue: https://github.com/rectorphp/rector/issues/8062

**Comment by aeberhard** [comment]
**Besser :)** Aber jetzt kommt ein anderer "Folgefehler"

![image](https://github.com/FriendsOfREDAXO/rexfactor/assets/330560/dab6e713-ac35-4757-8eed-9a15b17dc8e7)

mit folgender Änderung

`return $this->json['totals'] ?? [];`

klappt es ...

es kommt aber eine Warning

![image](https://github.com/FriendsOfREDAXO/rexfactor/assets/330560/b5db88c4-bfd9-41f9-a69f-6dab6b627144)

**Comment by aeberhard** [comment]
Mir ist gerade aufgefallen die obige **Warning** kommt auch bei anderen Use-Cases!

**Comment by aeberhard** [comment]
Ah die Warning kommt durch meine lokale Änderung

`return $this->json['totals'] ?? [];`

Wenn ich die wieder rausnehme kommt der Whoops bei allen Use-Cases

**Comment by staabm** [comment]
der error ist behoben im nächsten rector release mit https://github.com/rectorphp/rector-src/pull/4601

**Comment by staabm** [comment]
Sollte behoben sein

**Comment by aeberhard** [comment]
Jo passt jetzt!
