### ISSUE TITLE
redaxo.org infos pflegen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexfactor#23]
**Feature description / Feature Beschreibung**

auf https://redaxo.org/download/addons/rexfactor/ steht noch "coming soon".

wäre super dort ein paar sinnvolle texte zu haben.
falls in diesem zug noch inhaltlich sinnvolles abfällt, könnte man das auch gerne hier im repo in der readme ergänzen

**Comment by staabm** [comment]
@skerbis magst du dir das mal anschauen?

**Comment by skerbis** [comment]
Ja klar

**Comment by skerbis** [comment]
aktueller Stand ok?

**Comment by skerbis** [comment]
ich fand es bei diesem AddOn passend

**Comment by staabm** [comment]
ok danke
