### ISSUE TITLE
Ausgeführten use-case auf folgenden Ergebnis-Seiten anzeigen

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexfactor#41]
```
rexfactor
Migration preview
AddOn: developer

Target Version: R5.11+ compatible / PHP 7.2+

Diff Format: line-by-line

```

Hier sollte noch der ausgewählte/ausgeführte **use-case** angezeigt werden.

z.B. 
### Migration preview: Remove dead code

**Comment by aeberhard** [comment]
Dann weiss man auch welchen Button man vorher geklickt hat :))

**Comment by aeberhard** [comment]
![image](https://user-images.githubusercontent.com/330560/228949405-216c9c33-84d5-42aa-9cf6-c2467b922a44.png)

Hier sollte auch die Überschrift wie oben ausgegeben werden und die Meldung als Info-Meldung ausgegeben werden wie in den anderen Addons (rex_view::info())

**Comment by aeberhard** [comment]
Hier sollte auch die Überschrift wie oben ausgegeben werden

z.B.
### Migration: Remove dead code

**Es sollte immer ersichtlich sein wo ich bin, in welcher Migration.**

![image](https://user-images.githubusercontent.com/330560/229237706-65f8c0ba-e6de-41f2-a6af-792423997e56.png)

**Comment by staabm** [comment]
sollten wir so machen. gutes feedback. danke.
