### ISSUE TITLE
REDAXO Specific Code style - Problem mit Line-Endings?

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/rexfactor#42]
Es werden **alle** php-Dateien des Addons die bereits per VSCode den REDAXO-Code-Style haben
als Migration vorgeschlagen, es sind jedoch **keine Änderungen** ersichtlich

![image](https://user-images.githubusercontent.com/330560/229234292-8d59bd59-4450-4843-b8b1-abbb3ef58b37.png)

Hier aktuell unter Windows mit VSCode 
![image](https://user-images.githubusercontent.com/330560/229235207-a6c154ab-4101-4cc7-8722-01cf8778f7f2.png)

**Comment by aeberhard** [comment]
![image](https://user-images.githubusercontent.com/330560/229236533-ed640350-5125-48c2-8a8f-90f31fe4cb17.png)

**Comment by aeberhard** [comment]
Nach Anwendung der Migration:
![image](https://user-images.githubusercontent.com/330560/229236768-044b67b6-4613-4813-abd3-945421c36e78.png)

Github will aber dann doch wieder CRLF meine ich ... ?

**Comment by aeberhard** [comment]
@staabm @gharlan LF / CRLF sollte meiner Meinung nach nicht geändert werden. Oder was meint Ihr!?

**Comment by staabm** [comment]
> Github will aber dann doch wieder CRLF meine ich ... ?

Git selbst gibt es nicht vor. Auf windows benutzen aber manche  user das auto-CRLF git feature, wodurch newline zeichen ungewandelt werden.

Ich vermute der redaxo style hätte gerne LF. Rexfactor selbst verwendet 1:1 den php-cs-fixer mit dem redaxo-code-style, d.h. Rexfactor selbst verändert selbst nichts an den cs-fixer regeln/formattings.

Ob die vorschau richtig funktioniert wenn nur newlines sich ändern müsste ich testen.

**Comment by aeberhard** [comment]
Die Newlines werden aber durch die Migration geändert
vorher
![image](https://user-images.githubusercontent.com/330560/229312431-cdbe64bf-1435-4a87-9baf-3a3954d3e349.png)
nachher
![image](https://user-images.githubusercontent.com/330560/229312436-eb898491-f82d-44a6-aa9a-87bd15036bc4.png)

**Comment by gharlan** [comment]
Also im Repo sollen alle Dateien LF nutzen. Das haben wir so auch im CS-Fixer drin, denn in PRs wollen wir ja, dass CRLF bemängelt wird vom CS-Fixer.

Ich denke, das beste wäre, auto-CRLF in git zu deaktivieren, und dann auch auf Windows lokal LF im Source Code zu nutzen.
Wobei ich selbst ja kein Windows nutze, daher nicht ganz einschätzen kann, was insgesamt üblich/empfehlenswert ist.

Aber dass der CS-Fixer so konfiguriert ist, dass LF erzwungen wird, ist eigentlich so üblich. Und wie gesagt, als PR-Check will man das ja auch gerade erzwingen, um einheitliche Zeilenenden im Repo zu haben.

**Comment by aeberhard** [comment]
Muss ich mal checken, evtl. liegt es auch am VSCode dass da CRLF eingestellt ist.

**Comment by aeberhard** [comment]
VSCode kann man auch einstellen dass LF statt CRLF verwendet wird.
Mache hier mal zu :)
