### ISSUE TITLE
Default Target PHP setzen 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/rexfactor#46]
vielleicht automatisch direkt auf die Mindest-Version der aktuell verwendeten REDAXO-Version oder des AddOns (package.yml)

**Comment by staabm** [comment]
in meinen augen ist rexfactor ein devtool was man in einer lokalen redaxo installation verwendet um andere addons zu migrieren.

die redaxo installation die man dabei verwendet ist eigentlich nur eine "laufzeitumgebung" und hat in meinen augen keine direkte relevanz. ich verwende bewusst den konservativen ansatz die ältere target version zu verwenden, weil ich befürchte dass addon autoren gar nicht drauf achten und dann am ende durch verwenden der neueren target version aus unwissenheit BC breaks einbauen und die mindest versionen ohne grund erhöhen.

kleine mindest versionen sind aus ecosystem sicht eignentlich super.

ggf. könnte man die target version aber anhand des in der [package.yml verwendeten mindest-redaxo-version einstellen](https://github.com/FriendsOfREDAXO/graphql/blob/aad318827115032e4d135e8d8281ebf242b59fe5/package.yml#L16).
d.h. wenn ein addon bereits die höhere redaxo core version vorraussetzt dann auch die höhere mindest version im rexfactor annehmen

**Comment by skerbis** [comment]
Aktuell führt man eine Preview in PHP 7.2 aus. Erst dann kann ich ein anderes Target wählen. Das erscheint mir zeitraubend zu sein, will man z.B. auf 8 migrieren.

**Comment by staabm** [comment]
ich denke die wenigstens addons sollten/wollten target R5.15+ haben.
willst du in deinen addons tatsächlich kompatibilität mit R5.11+ nicht mehr haben?


> Das erscheint mir zeitraubend zu sein, will man z.B. auf 8 migrieren.

meinst du damit, dass du ein addon mit php8 kompatibel machen willst (php8 use-case) - oder dass du dein addon so einstellen willst dass php8 mindest vorraussetzung ist um es zu verwenden (R5.15 target version)?

**Comment by skerbis** [comment]
Ja würde dann bei einem refaktor möglichst hoch ansetzen. Redaxoversion wäre eher sekundär. Aber bei einer Modernisierung macht es Sinn direkt eine höhere php Version anzupeilen.

**Comment by staabm** [comment]
höhere php version anpeilen macht man im use-case. 

die mindest version anzuheben sollte man meiner meinung nach so selten wie möglich.
