### ISSUE TITLE
declare-strict-types als use-case?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/rexfactor#76]
**Feature description / Feature Beschreibung**
https://twitter.com/rectorphp/status/1649370645002858496

**Comment by aeberhard** [comment]
@staabm ich mache das jetzt bereits in jede PHP-Datei rein. Bin dafür :))

z.b. https://github.com/FriendsOfREDAXO/properties

**Comment by staabm** [comment]
strict types an sich find ich auch gut. ich bin am überlegen, ob jemand mit rexfactor sowas flächig in sein addon einbauen wollen würde, oder ob er von den vielen errors die darauffolgen erstmal verschreckt wäre :).

strict-types kann man alternativ übrigens auch mit dem [php-cs-fixer erzwingen](https://cs.symfony.com/doc/rules/strict/declare_strict_types.html)

**Comment by aeberhard** [comment]
Die Errors kommen ja nicht umsonst :)
Verbessert wird der Code dadurch auf jeden Fall! Und das ist ja auch das Ziel!

**Comment by aeberhard** [comment]
@staabm wie ist es bei Templates+Modulen?
Gibt es da evtl. Probleme? Dann sollte man den UseCase bei developer:templates+module ausblenden.

**Comment by staabm** [comment]
> Gibt es da evtl. Probleme? Dann sollte man den UseCase bei developer:templates+module ausblenden.

mir sind bisher keine bekannt. wenn du konkrete im kopf hast, gerne in neuem issue mit beispiel

**Comment by aeberhard** [comment]
Ich habe das jetzt mal ausprobiert. Soweit funktioniert alles. 
Dachte wenn in allen Templates+Modulen das declare drin ist gibt es Probleme.

Es wird aber z.Teil das declare doppelt ausgegeben. Ist ja aber bereits ein bekanntes Issue im Vendor!?

**Comment by aeberhard** [comment]
Und ich finde als eigenen Use-Case besser gegenüber CS-Fixer.
Eben wegen den von Dir angesprochenen Errors :)
